#!/bin/bash

# Function to load configuration from file or set defaults
load_config() {
    print_message $BLUE "Loading configuration..." true

    # Create config and log directories if they don't exist
    mkdir -p "$CONFIG_DIR" || { print_message $RED "FATAL: Could not create config directory $CONFIG_DIR. Exiting." true; exit 1; }
    mkdir -p "$SCRIPT_LOG_DIR" || { print_message $RED "FATAL: Could not create log directory $SCRIPT_LOG_DIR. Exiting." true; exit 1; }

    if [ ! -f "$CONFIG_FILE" ]; then
        run_setup_wizard
        # After the wizard runs, the config file should exist.
        if [ ! -f "$CONFIG_FILE" ]; then
            print_message $RED "FATAL: Configuration file not found after setup wizard. Exiting." true
            exit 1
        fi
    fi

    # Source the configuration file
    # Disable unbound variable errors temporarily if config is incomplete
    set +u
    . "$CONFIG_FILE"
    set -u # Re-enable unbound variable errors

    # --- Assign variables from config or use defaults if missing ---
    AZEROTHCORE_DIR="${AZEROTHCORE_DIR:-$DEFAULT_AZEROTHCORE_DIR}"
    BACKUP_DIR="${BACKUP_DIR:-$DEFAULT_BACKUP_DIR}"
    # Set DB_USER default based on whether USE_DOCKER is true
    USE_DOCKER="${USE_DOCKER:-$DEFAULT_USE_DOCKER}"
    if [ "$USE_DOCKER" = true ]; then
        DB_USER="${DB_USER:-$DEFAULT_DB_USER_DOCKER}"
    else
        DB_USER="${DB_USER:-$DEFAULT_DB_USER}"
    fi
    # DB_PASS is intentionally not defaulted here if empty in config, to force prompt.
    # However, if the var is COMPLETELY ABSENT from config, DEFAULT_DB_PASS ("") should be used.
    # The `:-` operator handles if the var is unset or null. If it's set to empty string in config, it remains empty.
    DB_PASS="${DB_PASS:-$DEFAULT_DB_PASS}"
    AUTH_DB_NAME="${AUTH_DB_NAME:-$DEFAULT_AUTH_DB_NAME}"
    CHAR_DB_NAME="${CHAR_DB_NAME:-$DEFAULT_CHAR_DB_NAME}"
    WORLD_DB_NAME="${WORLD_DB_NAME:-$DEFAULT_WORLD_DB_NAME}"

    local server_config_suffix="${SERVER_CONFIG_DIR_PATH_SUFFIX:-$DEFAULT_SERVER_CONFIG_DIR_PATH_SUFFIX}"
    local server_log_suffix="${SERVER_LOG_DIR_PATH_SUFFIX:-$DEFAULT_SERVER_LOG_DIR_PATH_SUFFIX}"

    AUTH_SERVER_LOG_FILENAME="${AUTH_SERVER_LOG_FILENAME:-$DEFAULT_AUTH_SERVER_LOG_FILENAME}"
    WORLD_SERVER_LOG_FILENAME="${WORLD_SERVER_LOG_FILENAME:-$DEFAULT_WORLD_SERVER_LOG_FILENAME}"
    ERROR_LOG_FILENAME="${ERROR_LOG_FILENAME:-$DEFAULT_ERROR_LOG_FILENAME}"
    SCRIPT_LOG_FILENAME="${SCRIPT_LOG_FILENAME:-$DEFAULT_SCRIPT_LOG_FILENAME}"

    POST_SHUTDOWN_DELAY_SECONDS="${POST_SHUTDOWN_DELAY_SECONDS:-$DEFAULT_POST_SHUTDOWN_DELAY_SECONDS}"
    CORES="${CORES_FOR_BUILD:-$DEFAULT_CORES_FOR_BUILD}" # CORES is the runtime var, CORES_FOR_BUILD is from config
    USE_DOCKER="${USE_DOCKER:-$DEFAULT_USE_DOCKER}"
    CRON_PATH="${CRON_PATH:-$DEFAULT_CRON_PATH}"

    # --- Assign non-user-configurable variables from defaults ---
    AUTH_PORT="${DEFAULT_AUTH_PORT}"
    WORLD_PORT="${DEFAULT_WORLD_PORT}"

    # --- Update dynamic paths based on loaded/defaulted AZEROTHCORE_DIR ---
    BUILD_DIR="$AZEROTHCORE_DIR/build"
    SERVER_CONFIG_DIR_PATH="$AZEROTHCORE_DIR/$server_config_suffix"
    SERVER_LOG_DIR_PATH="$AZEROTHCORE_DIR/$server_log_suffix"
    AUTH_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/authserver"
    WORLD_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/worldserver"


    # --- Configuration Migration/Update ---
    # If CRON_PATH is missing from an existing config, add it.
    if [ -z "$CRON_PATH" ]; then
        print_message $YELLOW "CRON_PATH not found in config, adding it now..." true
        local current_system_path
        current_system_path=$(echo "$PATH")
        save_config_value "CRON_PATH" "$current_system_path"
        # Reload the variable for the current session
        CRON_PATH="$current_system_path"
        print_message $GREEN "CRON_PATH has been saved to your configuration." true
        print_message $YELLOW "To apply this to an existing cron job, please re-run the 'Setup Automated Backup Schedule' option from the Backup Menu." true
    fi

    print_message $GREEN "Configuration loaded successfully." true
}

# Function to save the current configuration to the config file
save_config() {
    print_message $BLUE "Saving configuration..." true
    local temp_config_file="$CONFIG_DIR/ACrebuild.conf.tmp"

    # Capture the current PATH to be used by cron jobs
    local current_path
    current_path=$(echo "$PATH")

    # Create the config file content in a temporary file
    # This prevents leaving a corrupted or incomplete config file on error
    cat > "$temp_config_file" <<EOF
# ACrebuild Configuration File
# This file is automatically generated. Do not edit manually unless you know what you are doing.

AZEROTHCORE_DIR="$AZEROTHCORE_DIR"
BACKUP_DIR="$BACKUP_DIR"
DB_USER="$DB_USER"
DB_PASS="$DB_PASS"
AUTH_DB_NAME="$AUTH_DB_NAME"
CHAR_DB_NAME="$CHAR_DB_NAME"
WORLD_DB_NAME="$WORLD_DB_NAME"
SERVER_CONFIG_DIR_PATH_SUFFIX="$DEFAULT_SERVER_CONFIG_DIR_PATH_SUFFIX"
SERVER_LOG_DIR_PATH_SUFFIX="$DEFAULT_SERVER_LOG_DIR_PATH_SUFFIX"
AUTH_SERVER_LOG_FILENAME="$AUTH_SERVER_LOG_FILENAME"
WORLD_SERVER_LOG_FILENAME="$WORLD_SERVER_LOG_FILENAME"
ERROR_LOG_FILENAME="$ERROR_LOG_FILENAME"
POST_SHUTDOWN_DELAY_SECONDS="$POST_SHUTDOWN_DELAY_SECONDS"
CORES_FOR_BUILD="$CORES"
USE_DOCKER="$USE_DOCKER"
CRON_PATH="$current_path"
EOF

    if [ $? -eq 0 ]; then
        # Move the temporary file to the final destination
        mv "$temp_config_file" "$CONFIG_FILE"
        if [ $? -eq 0 ]; then
            chmod 600 "$CONFIG_FILE"
            print_message $GREEN "Configuration successfully saved to $CONFIG_FILE" true
            return 0
        else
            print_message $RED "FATAL: Could not move temp config file to $CONFIG_FILE." true
            rm -f "$temp_config_file"
            return 1
        fi
    else
        print_message $RED "FATAL: Could not write to temporary config file $temp_config_file." true
        rm -f "$temp_config_file"
        return 1
    fi
}

# Function to save a single configuration value to the config file
# This is useful for making small changes without rewriting the whole file.
save_config_value() {
    local key_to_save="$1"
    local value_to_save="$2"
    local temp_config_file="$CONFIG_DIR/ACrebuild.conf.tmp"

    # Ensure the config file exists before trying to modify it.
    if [ ! -f "$CONFIG_FILE" ]; then
        print_message $YELLOW "Config file not found. A new one will be created." true
        # Create a blank config file to avoid errors, assuming a full save will happen later.
        touch "$CONFIG_FILE" || { print_message $RED "FATAL: Could not create config file $CONFIG_FILE." true; return 1; }
        chmod 600 "$CONFIG_FILE"
    fi

    # Escape backslashes and double quotes for sed
    local escaped_value
    escaped_value=$(echo "$value_to_save" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

    # Check if the key exists and update it, otherwise append it.
    if grep -q "^${key_to_save}=" "$CONFIG_FILE"; then
        sed "s|^${key_to_save}=.*|${key_to_save}=\"${escaped_value}\"|" "$CONFIG_FILE" > "$temp_config_file" && mv "$temp_config_file" "$CONFIG_FILE"
    else
        echo "${key_to_save}=\"${escaped_value}\"" >> "$CONFIG_FILE"
    fi

    if [ $? -eq 0 ]; then
        print_message $GREEN "Configuration value '$key_to_save' updated." false
    else
        print_message $RED "Error updating '$key_to_save' in $CONFIG_FILE." true
        rm -f "$temp_config_file"
        return 1
    fi
    return 0
}

# Function to ask the user where their AzerothCore is installed
# This function is called AFTER load_config() has run at least once.
ask_for_core_installation_path() {
    local current_ac_dir="$AZEROTHCORE_DIR" # From loaded config
    echo ""
    print_message $YELLOW "AzerothCore Installation Path Setup" true
    print_message $CYAN "The current AzerothCore directory is set to: $current_ac_dir" false
    print_message $YELLOW "Press ENTER to keep the current path, or enter a new path:" false
    read -r user_input_path

    if [ -n "$user_input_path" ] && [ "$user_input_path" != "$current_ac_dir" ]; then
        print_message $YELLOW "You entered a new path: $user_input_path" false
        # Basic validation: check if directory exists (optional, could be a new setup)
        if [ ! -d "$user_input_path" ]; then
            print_message $YELLOW "Warning: The specified directory does not currently exist." false
            print_message $YELLOW "Make sure it's correct if you proceed to save." false
        fi

        print_message $YELLOW "Save this new path to the configuration file? (y/n)" true
        read -r save_choice
        if [[ "$save_choice" =~ ^[Yy]$ ]]; then
            save_config_value "AZEROTHCORE_DIR" "$user_input_path"
            if [ $? -eq 0 ]; then
                print_message $GREEN "AzerothCore directory saved to configuration." true
                # Reload config to update all related paths and variables
                print_message $CYAN "Reloading configuration to apply changes..." false
                load_config
            else
                print_message $RED "Failed to save AzerothCore directory. Using runtime value: $user_input_path" true
                # Manually update runtime AZEROTHCORE_DIR and related paths for current session if save failed
                AZEROTHCORE_DIR="$user_input_path"
                BUILD_DIR="$AZEROTHCORE_DIR/build"
                SERVER_CONFIG_DIR_PATH="$AZEROTHCORE_DIR/$DEFAULT_SERVER_CONFIG_DIR_PATH_SUFFIX"
                SERVER_LOG_DIR_PATH="$AZEROTHCORE_DIR/$DEFAULT_SERVER_LOG_DIR_PATH_SUFFIX"
                AUTH_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/authserver"
                WORLD_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/worldserver"
            fi
        else
            print_message $CYAN "New path will be used for this session only." false
            # Manually update runtime AZEROTHCORE_DIR and related paths for current session
            AZEROTHCORE_DIR="$user_input_path"
            BUILD_DIR="$AZEROTHCORE_DIR/build"
            SERVER_CONFIG_DIR_PATH="$AZEROTHCORE_DIR/$DEFAULT_SERVER_CONFIG_DIR_PATH_SUFFIX"
            SERVER_LOG_DIR_PATH="$AZEROTHCORE_DIR/$DEFAULT_SERVER_LOG_DIR_PATH_SUFFIX"
            AUTH_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/authserver"
            WORLD_SERVER_EXEC="$AZEROTHCORE_DIR/env/dist/bin/worldserver"
        fi
    elif [ -z "$user_input_path" ]; then
        print_message $GREEN "Keeping current path: $current_ac_dir" false
    else
        print_message $GREEN "Path unchanged: $current_ac_dir" false
    fi

    # Display final active paths (these are now set by load_config if save was successful, or manually if not)
    print_message $BLUE "Effective paths for this session:" true
    print_message $GREEN " AzerothCore Directory: $AZEROTHCORE_DIR" false
    print_message $GREEN " Build Directory:       $BUILD_DIR" false
    print_message $GREEN " Auth Server Exec:    $AUTH_SERVER_EXEC" false
    print_message $GREEN " World Server Exec:   $WORLD_SERVER_EXEC" false
    print_message $GREEN " Server Config Dir:   $SERVER_CONFIG_DIR_PATH" false
    print_message $GREEN " Server Log Dir Path: $SERVER_LOG_DIR_PATH" false
    echo ""
}
